apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heartbeat-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lucasrangelt/DevOpsLearningLab.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: heartbeat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true